### ISSUE TITLE
Possible Synchronous Version

### ISSUE THREAD

**Issue by knightebsuku** [j0rsa/transmission-rpc#19]
Hi There

I'm trying to use this library and was wondering is a sync version would be available?
I'm busy creating a GUI (Gtk) application and need the transmission part to run in a background thread. I'm not sure how to go about having async in a thread especially in a context with a GUI application.

Do you have any suggestions on how I can achieve this?

**Comment by George-Miao** [comment]
Hi! Just trying to use the lib under async environment. And because concurrency is needed, the fact that the `TransClient` is taking `&mut self` is quite annoying because it means I have to guarantee there's only one requesting being sent at one time. I think potentially `TransClient::session_id` can be changed (or make another `SyncTransClient` because this does add additional runtime cost) to an `Arc<RwLock<String>>` or something similar so that exposed functions(essentially `TransClient::call`) uses `&self`.

**Comment by red-avtovo** [comment]
Hi @knightebsuku! Not sure if it still relevant to you, but just wanted to let you know that the respectful PR has been just merged and now you can use the library in a synchronous way

**Comment by knightebsuku** [comment]
Hi @red-avtovo
This is great. Thanks a lot for implementing this.

**Comment by red-avtovo** [comment]
Kudos to @George-Miao
